### ISSUE TITLE
Add support for HTML5 playing video

### ISSUE THREAD

**Issue by breedx2** [breedx2/cuspid#12]
The texture should also be able to support rendering of HTML5 video.

Three.js Image docs refer to this:  http://threejs.org/docs/#Reference/Textures/Texture

**Comment by zkarcher** [comment]
Looks like there's a `VideoTexture` class. Live example is here: http://threejs.org/examples/webgl_video_panorama_equirectangular.html

**Comment by breedx2** [comment]
Now supported!
