### ISSUE TITLE
Add support for multiple translucent textures

### ISSUE THREAD

**Issue by breedx2** [breedx2/cuspid#15]
Each one could be running its own animation(s), but rendered with some translucence.

**Comment by zkarcher** [comment]
Do you want to render the black (or white) pixels as transparent? Or, will the source images have transparency?

**Comment by breedx2** [comment]
I was thinking something akin to having multiple layers in phtotoshop and changing layer transparency.  The source images would typically still be opaque.

**Comment by breedx2** [comment]
Resolved by #112 after > 4 years!  Will follow up with some more minor completeness issues.
