### ISSUE TITLE
Add support for a series of images to box scroll

### ISSUE THREAD

**Issue by breedx2** [breedx2/cuspid#17]
Would like to be able to have more than one image scrolling by.  Subsequent images "train" on after the previous one.

**Comment by zkarcher** [comment]
I feel like the simplest way to do this is: add multiple quad's to the scene, and move them around. This is not difficult, it's just different from the current version (right now, it's rendering one big quad that never moves.)

**Comment by breedx2** [comment]
Yup, I agree!

**Comment by breedx2** [comment]
This has been addressed in PR #32
