### ISSUE TITLE
Box scroll zoom out can zoom out too far

### ISSUE THREAD

**Issue by breedx2** [breedx2/cuspid#19]
We should prevent box scroll zoom from zooming out too far, which causes black to appear at the borders.

**Comment by zkarcher** [comment]
I can't reproduce this. Maybe my window is the wrong size. Do you have a screenshot?

**Comment by breedx2** [comment]
Just hitting Z and shift-Z to zoom in and out:  https://www.youtube.com/watch?v=Xqbxqf3qC1U

**Comment by breedx2** [comment]
This should be addressed in #23
