### ISSUE TITLE
Video has black areas

### ISSUE THREAD

**Issue by breedx2** [breedx2/cuspid#56]
I've only tried with one video so far, but it seems like very bright areas are becoming black.  Something in the shader perhaps.  It's ugly.

**Comment by zkarcher** [comment]
That sounds like a shader bug. Is this only reproducible on certain shaders/effects?

**Comment by breedx2** [comment]
I think it's a shader bug too (the shader is still a bit black magic for me!).  There's only the one shader being used right now I think...

**Comment by breedx2** [comment]
Fixed.
