### ISSUE TITLE
Allow changing of GL scaling/interpolation mode?

### ISSUE THREAD

**Issue by breedx2** [breedx2/cuspid#9]
I'm probably using the wrong terminology here, but there should be a way to change the way that Three.js scales up the images, and the user should be able to toggle between modes (as an animation option, perhaps?).  I like the aesthetic of non-interpolated zooming/scaling, and it would be great to bring that back in some capacity.

Maybe this is related to Texture.magFilter = THREE.NearestFilter?

**Comment by zkarcher** [comment]
I believe that's the correct terminology... WebGL gives you a little control over this. In cuspid.js -> init3D() method, lines 37 & 38 set the texture's .minFilter and .magFilter . Try commenting out the line with "Three.LinearFilter" (smoother) and uncomment the line with "Three.NearestFilter" (pixelated).

I like the pixelated version, tho it doesn't resemble the original <canvas> scaling. If you want that effect, scale the texture to a huge size (maybe 4096x4096) in GIMP/Photoshop using cubic interpolation, and see how that looks :)

I like the idea of a keyboard toggle setting the interpolation mode. I'll take this on.
